### ISSUE TITLE
Compilation fails under Linux mint 17.2

### ISSUE THREAD

**Issue by Royal-Jelly** [eviltrout/tis-100#8]
royal-jelly@royaljelly-MS-7693 ~/Repositories/tis-100.git/trunk $ make
gcc -std=c99 -pedantic -Wall -pedantic-errors -Wundef -Wstrict-prototypes  -Wmissing-declarations -c src/program.c -o build/program.o
src/program.c:12:20: fatal error: curses.h: No such file or directory
 #include "curses.h"
                    ^
compilation terminated.
make: **\* [build/program.o] Error 1

**Comment by minkezhang** [comment]
You need the curses C lib: http://askubuntu.com/questions/78749/what-provides-curses-headers-named-curses-h

Probs should add a note about dependencies in the README

**Comment by Royal-Jelly** [comment]
thank you for pointing that out, works great now
